# Generated by Django 5.2.5 on 2025-08-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = []

	operations = [
		migrations.CreateModel(
			name='Variant',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('name', models.CharField(max_length=255)),
				(
					'cost_price',
					models.DecimalField(decimal_places=2, max_digits=10),
				),
				(
					'selling_price',
					models.DecimalField(decimal_places=2, max_digits=10),
				),
			],
		),
	]
