# Generated by Django 5.2.5 on 2025-08-23 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		('variant', '0001_initial'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name='Order',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('created_at', models.DateTimeField(auto_now_add=True)),
				(
					'customer',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='orders',
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
		),
		migrations.CreateModel(
			name='OrderItem',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('quantity', models.PositiveIntegerField()),
				(
					'price',
					models.DecimalField(decimal_places=2, max_digits=10),
				),
				(
					'order',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='items',
						to='order.order',
					),
				),
				(
					'variant',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to='variant.variant',
					),
				),
			],
		),
	]
